### PR TITLE
Remove hamburger menu

### LINKED ISSUE #54: Add Navbar like papermod (Remove Hamburger menu)
Take a look at [this theme](https://adityatelange.github.io/hugo-PaperMod/). I like the overall look and feel and I think I will add a color-theme similar to this. 

I always hated hamburger menus on mobile. They are not good for accessibility. This `Hugo-papermod` theme has done a good approach and I like it. 

I think we can let the users have the option to choose if they want to have this hamburger menu or not.

### PR DESCRIPTION
**Pull request by rohandebsarkar**
closes #54.

This can only be merged after #53.

@pourmand1376, I replaced the hamburger menu completely with a normal always visible menu (no JavaScript). I did not keep an option since in the long run it might be difficult to maintain two menus.

### CODE REVIEW

**Comment by pourmand1376** [comment]
I think maybe it is better not to show header social icons for mobile at all. They are too small. 

Also, navbar items are too small. They are hard to click in mobile. A little padding and maybe a bigger size would help. 

I have to add more menus to see how this theme handles more menus.

**Comment by rohandebsarkar** [comment]
Increased header font size. Added more padding to social icons, increased their size to 1.25x of font size.

**Comment by pourmand1376** [comment]
Sorry for the delay. I am under some harsh deadlines which I have to meet. I will be available next week.

**Comment by pourmand1376** [comment]
Thanks again for adding these changes. It looks good on a laptop and tablet. Although I think the padding can be a little bit smaller on big-size monitors (but it is good for mobile). 
 
The only noticeable problem is the dark/light mode icon. If we place it near the website name, we would have lots of extra space for menus. 

image
image

image

**Comment by pourmand1376** [comment]
I fixed the bug myself. Maybe there are some issues with tailwindcss as I do not know much about it. But, It looks good.

**Comment by rohandebsarkar** [comment]
Thanks for the fix, but the problem now seems to be that the theme toggle button is not in a very noticeable place in the desktop version.

**Comment by pourmand1376** [comment]
I think now it should be better. I added a vertical line to make it more clear.

If you are not satisfied with the overall look and feel, we can use the old way (like al-folio).

**Comment by rohandebsarkar** [comment]
I have taken your suggestions, and adjusted the menu. I have refactored some of the lists those were being used there. I think this fixes the concerns you had. Feel free to get back if any other changes are required.

**Comment by pourmand1376** [comment]
> I have taken your suggestions and adjusted the menu. I have refactored some of the lists that were being used there. I think this fixes the concerns you had. Feel free to get back if any other changes are required.

Thanks for the suggestions and fixes. I really appreciate it. 

I consulted with a UI/UX designer about this and she says that there is too much data in the header. Also, I see that there is some overlap between icons. 
image

The current hamburger menu is fine with the design. It is just that I don't like it. I can see that this is not our top priority. Let's just keep this one open for a while until I get good results. It may also take a while ...

**Comment by rohandebsarkar** [comment]
Yeah, you are right there are a lot of information in the header right now, this actually follows from al-folio. 

On the icons overlap, I can't see it on my devices. Can you tell me the screen width of your device?

**Comment by rohandebsarkar** [comment]
Pushed some changes. Better positioning on the theme button using absolute. Fixed icon overlapping issue (if there are more social icons than the maximum the screen can accommodate it will have an overflow scroll).

**Comment by pourmand1376** [comment]
This is surprisingly good. 
image

I also removed this y-scroll bar.

**Comment by pourmand1376** [comment]
Just another minor improvement. 

We should add more space for the horizontal scrollbars. It is inside the word. It should be farther.
image

Like this
image

**Comment by rohandebsarkar** [comment]
For adding space to the scrollbar, we would have to give y-padding to the links. This will increase the height of the navbar.

**Comment by pourmand1376** [comment]
Okay, Let's merge it. I will deal with it later.

**Review by pourmand1376 — APPROVED** [review]

**Pull request merged**
