### PR TITLE
Add Pre-commit check

### PR DESCRIPTION
**Pull request by pourmand1376**
I explained about this one [here](https://github.com/alshedivat/al-folio/pull/801). Unfortunately, It is currently not configured properly in al-folio, so we do not use it effectively. 

You can see [here](https://major.homeonderanged.org/post/hugo-pre-commit/) on why it is important. 

To put it in a nutshell: you should install bot from [here](https://pre-commit.ci/) to make it work.

### CODE REVIEW

**Comment by pourmand1376** [comment]
I now added the functionality to fix typos in the code by adding [this one](https://github.com/crate-ci/typos/blob/master/docs/pre-commit.md).

**Review by rohandebsarkar — APPROVED** [review]
Excellent addition, will save a lot of effort in the future.

**Comment by pourmand1376** [comment]
It is good that you like this. Please merge it when you successfully added the bot and we are good to go.

**Comment by rohandebsarkar** [comment]
Just a small question about how this works. Will it work before every commit locally?

**Comment by rohandebsarkar** [comment]
Closed by mistake.

**Comment by pourmand1376** [comment]
> Just a small question about how this works. Will it work before every commit locally?

Yes, If you install it locally, it would work locally, and check and fix before every commit. 

However, since we have PRs and users may not install this tools and their device, we should use the bot.

**Comment by rohandebsarkar** [comment]
Sorry, unable to follow. Which bot are you referring to?

**Comment by pourmand1376** [comment]
> Sorry, unable to follow. Which bot are you referring to?

https://pre-commit.ci/

You should install this bot on repo.

Sorry to include all this information at once. It is hard to digest :)

**Comment by rohandebsarkar** [comment]
done!

**Pull request merged**
